import boards from "./boards.json"
import { writeFile } from "node:fs/promises"

const literal = (value: string) => `'${value.replace(/'/g, "''")}'`
const json = (value: unknown) => `${literal(JSON.stringify(value))}::jsonb`

const rows = boards.map(
    ({ dateKey, size, letters, time, totalWords }) =>
        `(${literal(dateKey)}, ${size}, ${json(letters.split(""))}, ${time}, ${json(totalWords)})`
)

const sql = [
    "-- Custom SQL migration file, put your code below! --",
    "-- generated by scripts/boards/writeSeedMigration.ts from scripts/boards/boards.json",
    'INSERT INTO "boards" ("date_key", "size", "letters", "time", "total_words") VALUES',
    rows.join(",\n"),
    'ON CONFLICT ("date_key") DO NOTHING;',
    "",
].join("\n")

await writeFile("./migrations/0005_seed_boards.sql", sql)

console.log(`wrote ${rows.length} rows to migrations/0005_seed_boards.sql`)
